version: '3.8'
services: 
  postgresql: 
    image: postgres 
    container_name: BancoDeDados
    environment: 
      POSTGRES_USER: bootcamp
      POSTGRES_PASSWORD: bootcamp
      POSTGRES_DB: bootcamp
    ports: 
      - "5433:5432"
    